version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: book_db
    restart: always
    environment:
        MYSQL_USER: saptak
        MYSQL_PASSWORD: saptak
        MYSQL_DATABASE: book_db
        MYSQL_ROOT_PASSWORD: saptak_root
    ports:
      # port exposed : mysql port running inside container
      - "3306:3306"
